# Generated by Django 4.2 on 2023-06-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое название - что переделывает этот RemakeItem', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Подробное описание того, что этот тег должен делать.Описание желательно составлять так, чтобы другой человек мог понять как это работает и свою ошибку, если она есть и исправить ее')),
                ('latex_reqex', models.TextField(help_text='Регулярное выражение, вычленяющее содержимое тэга/команды')),
                ('html_format_str', models.TextField(blank=True, help_text='Текст, содержащий шаблоны и операторы форматирорования строк (в них вставится текст, вытащенный из latex_reqex)')),
                ('child_items', models.ForeignKey(default=0, help_text='Заполняется, если тег имеет подтеги', on_delete=django.db.models.deletion.CASCADE, to='latex2html.remakeitem')),
            ],
        ),
    ]
