# Generated by Django 4.2 on 2023-06-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0002_remakeitem_is_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remakeitem',
            old_name='child_items',
            new_name='child_item',
        ),
    ]
