# Generated by Django 4.2 on 2023-06-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0003_rename_child_items_remakeitem_child_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remakeitem',
            name='child_item',
            field=models.ForeignKey(help_text='Заполняется, если тег имеет подтеги', null=True, on_delete=django.db.models.deletion.CASCADE, to='latex2html.remakeitem'),
        ),
    ]
