# Generated by Django 4.2 on 2023-06-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0004_alter_remakeitem_child_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='remakeitem',
            name='immutable',
            field=models.BooleanField(default=False, help_text='Ставить true для тех тегов, для которых важны отступы'),
        ),
    ]
