# Generated by Django 4.2 on 2023-06-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0005_remakeitem_immutable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remakeitem',
            name='immutable',
        ),
    ]
