# Generated by Django 4.2 on 2023-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0006_remove_remakeitem_immutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remakeitem',
            name='is_head',
            field=models.BooleanField(help_text='Это значение равно True только у самостоятельных тегов, например, у тега itemize, но не у тега item. Также, с помощью этого значения можно выставить порядок выполнения преобразований.'),
        ),
    ]
