# Generated by Django 4.2 on 2023-06-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latex2html', '0007_alter_remakeitem_is_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remakeitem',
            name='child_item',
            field=models.ForeignKey(blank=True, help_text='Заполняется, если тег имеет подтеги', null=True, on_delete=django.db.models.deletion.CASCADE, to='latex2html.remakeitem'),
        ),
    ]
