version: '3.8'

services:
  db:
    build:
      context: .
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - config/.pg.env.dev
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - config/.env.dev
    depends_on:
      - db
    links:
      - db

volumes:
  postgres_data: