# Generated by Django 4.2 on 2023-05-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('graph_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='graph_id')),
                ('data', models.TextField(verbose_name='data')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
            options={
                'permissions': (('can_edit_nodes', 'Can edit graph nodes'), ('can_add_notes_to', 'Can add notes to graph node')),
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('rsrch_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='rsrch_id')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(help_text='Дата начала работы над исследованием', verbose_name='start_date')),
                ('end_date', models.DateField(help_text='Планируемая дата окончания работы над исследованием', verbose_name='end_date')),
                ('researchers', models.ManyToManyField(db_table='researches_users_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_add_researchers_to', 'Can add researchers to research'), ('can_add_graphs_to', 'Can add graphs to research')),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='note_id')),
                ('url', models.URLField(verbose_name='url')),
                ('note_type', models.CharField(max_length=20, verbose_name='note_type')),
                ('research_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.research')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodesNotesRelation',
            fields=[
                ('id', models.IntegerField(help_text='просто идентификатор строки', primary_key=True, serialize=False, verbose_name='id')),
                ('node_id', models.IntegerField(verbose_name='node_id')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.graph')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.note')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='research_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.research'),
        ),
    ]
