# Generated by Django 4.2 on 2023-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='data',
            field=models.TextField(blank=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='nodesnotesrelation',
            name='node_id',
            field=models.CharField(max_length=3, verbose_name='node_id'),
        ),
    ]
