# Generated by Django 4.2 on 2023-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nodesnotesrelation_unique_note_in_graph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='graph_id'),
        ),
        migrations.AlterField(
            model_name='nodesnotesrelation',
            name='id',
            field=models.AutoField(help_text='просто идентификатор строки', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
