# Generated by Django 4.2 on 2023-05-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_graph_graph_id_alter_nodesnotesrelation_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nodesnotesrelation',
            name='unique note in node',
        ),
    ]
