# Generated by Django 4.2 on 2023-05-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_nodesnotesrelation_unique_note_in_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesnotesrelation',
            name='graph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.graph'),
        ),
        migrations.AlterField(
            model_name='nodesnotesrelation',
            name='note_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.note'),
        ),
    ]
