# Generated by Django 4.2 on 2023-05-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_nodesnotesrelation_graph_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesnotesrelation',
            name='graph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph'),
        ),
    ]
