# Generated by Django 4.2 on 2023-05-30 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_graph_data_alter_nodesnotesrelation_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
    ]
