# Generated by Django 4.2 on 2023-05-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_research_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='research_id',
            new_name='rsrch_id',
        ),
    ]
