# Generated by Django 4.2 on 2023-05-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_research_id_note_rsrch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='research_id',
            new_name='rsrch_id',
        ),
    ]
