# Generated by Django 4.2 on 2023-06-02 00:26

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_research_id_graph_rsrch_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodesnotesrelation',
            options={'verbose_name': 'Node-Notes relation', 'verbose_name_plural': 'Node-Notes relations'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'permissions': (('can_add_researchers_to', 'Can add researchers to research'), ('can_add_graphs_to', 'Can add graphs to research')), 'verbose_name_plural': 'Researches'},
        ),
        migrations.AddField(
            model_name='user',
            name='computed_full_name',
            field=computed_property.fields.ComputedCharField(compute_from='get_full_name', default='name', editable=False, help_text='вычисляемое поле, на основе которого строится индекс для поисковых подсказок', max_length=200),
            preserve_default=False,
        ),
    ]
