# Generated by Django 4.2 on 2023-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_nodesnotesrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='note_type'),
        ),
    ]
