# Generated by Django 4.1.7 on 2023-04-05 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='rsrch_id')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateField(help_text='Дата начала работы над исследованием', verbose_name='start_date')),
                ('end_date', models.DateField(help_text='Планируемая дата окончания работы над исследованием', verbose_name='end_date')),
            ],
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.AlterField(
            model_name='user',
            name='study_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='study_group'),
        ),
        migrations.AddField(
            model_name='research',
            name='researchers',
            field=models.ManyToManyField(db_table='researches_users_relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
