# Generated by Django 4.2 on 2023-04-07 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_research_delete_researcher_alter_user_study_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='note_id')),
                ('url', models.URLField(verbose_name='url')),
                ('type', models.CharField(max_length=20, verbose_name='note_type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='graph_id')),
                ('data', models.TextField(verbose_name='data')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('research_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.research')),
            ],
        ),
    ]
