# Generated by Django 4.1.7 on 2023-04-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_graph_graph_id_rename_id_note_note_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodesNotesRelation',
            fields=[
                ('id', models.IntegerField(help_text='просто идентификатор строки', primary_key=True, serialize=False, verbose_name='id')),
                ('node_id', models.IntegerField(verbose_name='node_id')),
                ('graph_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.graph')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.note')),
            ],
        ),
    ]
