# Generated by Django 4.1.7 on 2023-04-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nodesnotesrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesnotesrelation',
            name='graph_id',
        ),
        migrations.RemoveField(
            model_name='nodesnotesrelation',
            name='note_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='research',
            name='researchers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='NodesNotesRelation',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
